
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      # We use our own convention for now
      # - id: name-tests-test
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: check-added-large-files
      - id: detect-private-key

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0
    hooks:
      - id: pyupgrade
        args: [--py311-plus]

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
    -   id: autoflake
        args: [--remove-all-unused-imports, --in-place]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: "\\.(py)$"
        args: [--settings-path=pyproject.toml]

# Disabled for now
  # - repo: https://github.com/psf/black
  #   rev: 24.4.2
  #   hooks:
  #     - id: black
  #       args: [--line-length=99]

  # - repo: https://github.com/pycqa/flake8
  #   rev: 7.1.0
  #   hooks:
  #     - id: flake8
  #       args: [--max-line-length=99, "--ignore=E203,W503,W605,E501,E701,F722,F821", "--extend-select=B950"]
  #       additional_dependencies:
  #         - flake8-bugbear
  #         - flake8-comprehensions
  #         - flake8-simplify
  #         - flake8-builtins
  #         - flake8-return
